# Numpy

Материалы:
* Макрушин С.В. "Лекция 1: Библиотека Numpy"
* https://numpy.org/doc/stable/user/index.html
* https://numpy.org/doc/stable/reference/index.html

## Задачи для совместного разбора

In [372]:
import numpy as np

1. Сгенерировать двухмерный массив `arr` размерности (4, 7), состоящий из случайных действительных чисел, равномерно распределенных в диапазоне от 0 до 20. Нормализовать значения массива с помощью преобразования вида  $𝑎𝑥+𝑏$  так, что после нормализации максимальный элемент масcива будет равен 1.0, минимальный 0.0

In [373]:
import random

def norm(array, element):
    return (element - min(array)) / (max(array) - min(array))


arr = np.array([[random.random()*random.randint(0,20) for i in range (7)] for i in range(4)])


print(arr)

for i in range(len(arr)):
    for j in range(len(arr[i])):
        arr[i][j] = norm(arr[i], arr[i][j])

print(arr)


[[ 1.49352142  2.0078714   1.16424901  3.14341498 15.89737306  0.76072377
   0.6793008 ]
 [ 0.43019881  2.7729501  14.05497778 14.51136758  0.99281763  7.54559886
   1.63975545]
 [ 0.36638062  0.78021833  2.69539705  0.          0.2931992  13.5772979
  15.81134262]
 [ 7.4012007   6.38180609  0.          0.          7.60296795  4.88155533
   7.59846283]]
[[0.05350353 0.12335168 0.07010569 0.19502253 1.         0.74719797
  0.66117232]
 [0.         0.19108813 0.9685495  1.         0.13157572 1.
  1.        ]
 [0.02317201 0.04934548 0.17047237 0.         0.0185436  0.8587062
  1.        ]
 [0.97346204 0.83938353 0.         0.         1.         0.64243985
  1.        ]]


2. Создать матрицу 8 на 10 из случайных целых (используя модуль `numpy.random`) чисел из диапозона от 0 до 10 и найти в ней строку (ее индекс и вывести саму строку), в которой сумма значений минимальна.

In [374]:
rng = np.random.default_rng()

arr2 = np.array([rng.integers(low=0, high=10, size=10) for i in range(8)])

print(arr2)

suM = [np.sum(i) for i in arr2]

miN = suM.index(np.min(suM))

print(miN, arr2[miN])

[[4 1 5 5 3 6 4 6 8 2]
 [2 8 9 0 2 8 9 6 7 0]
 [2 3 9 6 6 3 9 0 3 3]
 [7 1 4 3 3 1 9 0 2 5]
 [4 2 4 4 8 6 0 8 2 6]
 [1 2 3 0 2 7 5 8 5 1]
 [0 0 1 0 9 3 0 1 0 0]
 [3 6 6 9 4 6 5 4 3 7]]
6 [0 0 1 0 9 3 0 1 0 0]


3. Найти евклидово расстояние между двумя одномерными векторами одинаковой размерности.

In [375]:
a = np.array((-6, 3, 1))
b = np.array((413, 61, -341))

np.linalg.norm(a - b)

543.9567997552747

4. Решить матричное уравнение `A*X*B=-C` - найти матрицу `X`. Где `A = [[-1, 2, 4], [-3, 1, 2], [-3, 0, 1]]`, `B=[[3, -1], [2, 1]]`, `C=[[7, 21], [11, 8], [8, 4]]`.

In [376]:
A = np.matrix([[-1, 2, 4], [-3, 1, 2], [-3, 0, 1]])
B = np.matrix([[3, -1], [2, 1]])
C = np.matrix([[7, 21], [11, 8], [8, 4]])

print(np.linalg.inv(A) * -C * np.linalg.inv(B))



[[ 1.00000000e+00  5.32907052e-16]
 [-2.00000000e+00  1.00000000e+00]
 [ 3.00000000e+00 -4.00000000e+00]]


## Лабораторная работа №1

Замечание: при решении данных задач не подразумевается использования циклов или генераторов Python, если в задании не сказано обратного. Решение должно опираться на использования функционала библиотеки `numpy`.

1. Файл `minutes_n_ingredients.csv` содержит информацию об идентификаторе рецепта, времени его выполнения в минутах и количестве необходимых ингредиентов. Считайте данные из этого файла в виде массива `numpy` типа `int32`, используя `np.loadtxt`. Выведите на экран первые 5 строк массива.

In [377]:
minutes_n = np.loadtxt("minutes_n_ingredients.csv", dtype="int32", delimiter=',', skiprows=1)
minutes_n[:5,:]
origin = minutes_n

2. Вычислите среднее значение, минимум, максимум и медиану по каждому из столбцов, кроме первого.

In [378]:
shaped = [minutes_n[:, i] for i in range(1, len(minutes_n[0]))]

for i in shaped:
    print(f'min {np.min(i)} max {np.max(i)} med {np.median(i)}')


min 0 max 2147483647 med 40.0
min 1 max 39 med 9.0


3. Ограничьте сверху значения продолжительности выполнения рецепта значением квантиля $q_{0.75}$. 

In [379]:
##### 
q0_75 = np.quantile(minutes_n[:, 1], 0.75)
minutes_n[:, 1] = np.clip(minutes_n[:, 1], None, q0_75)
minutes_n

array([[127244,     60,     16],
       [ 23891,     25,      7],
       [ 94746,     10,      6],
       ...,
       [498432,     65,     15],
       [370915,      5,      4],
       [ 81993,     65,     14]])

4. Посчитайте, для скольких рецептов указана продолжительность, равная нулю. Замените для таких строк значение в данном столбце на 1.

In [380]:
print( (minutes_n == 0).sum() )
minutes_n[:, 1] = np.where(minutes_n[:, 1] == 0, 1, minutes_n[:, 1])
minutes_n

479


array([[127244,     60,     16],
       [ 23891,     25,      7],
       [ 94746,     10,      6],
       ...,
       [498432,     65,     15],
       [370915,      5,      4],
       [ 81993,     65,     14]])

5. Посчитайте, сколько уникальных рецептов находится в датасете.

In [381]:
len( np.unique(minutes_n[:, 0]) )

100000

6. Сколько и каких различных значений кол-ва ингредиентов присутвует в рецептах из датасета?

In [382]:
u, c =  np.unique(minutes_n[:, 2], return_counts=True)
dict(zip( u, c ))


{1: 13,
 2: 926,
 3: 2895,
 4: 5515,
 5: 7913,
 6: 9376,
 7: 10628,
 8: 10951,
 9: 10585,
 10: 9591,
 11: 8297,
 12: 6605,
 13: 4997,
 14: 3663,
 15: 2595,
 16: 1767,
 17: 1246,
 18: 790,
 19: 573,
 20: 376,
 21: 217,
 22: 161,
 23: 105,
 24: 69,
 25: 50,
 26: 28,
 27: 16,
 28: 16,
 29: 12,
 30: 12,
 31: 3,
 32: 1,
 33: 2,
 34: 1,
 35: 3,
 37: 1,
 39: 1}

7. Создайте версию массива, содержащую информацию только о рецептах, состоящих не более чем из 5 ингредиентов.

In [383]:
minutes_n[minutes_n[:, 2]<=5]

array([[446597,     15,      5],
       [204134,      5,      3],
       [ 25623,      6,      4],
       ...,
       [ 52088,     60,      5],
       [128811,     15,      4],
       [370915,      5,      4]])

8. Для каждого рецепта посчитайте, сколько в среднем ингредиентов приходится на одну минуту рецепта. Найдите максимальное значение этой величины для всего датасета

In [384]:
sum( minutes_n[:, 2] / minutes_n[:, 1] ) / len(minutes_n), np.max( minutes_n[:, 2] / minutes_n[:, 1] )

(0.3983000355849976, 24.0)

9. Вычислите среднее количество ингредиентов для топ-100 рецептов с наибольшей продолжительностью

In [385]:
minutes_n

array([[127244,     60,     16],
       [ 23891,     25,      7],
       [ 94746,     10,      6],
       ...,
       [498432,     65,     15],
       [370915,      5,      4],
       [ 81993,     65,     14]])

In [386]:
# top_100 = minutes_n[minutes_n[:, 1].argsort()][:-101:-1, :]
top_100 = np.flip( minutes_n[minutes_n[:, 1].argsort()], 0)[:100, :]
np.average( top_100[:, 2] )

9.96

10. Выберите случайным образом и выведите информацию о 10 различных рецептах

In [387]:
rnd = np.random.default_rng().integers(len(minutes_n), size=10)
print(rnd)
minutes_n[rnd]

[61901 81587 19478 22335 29157 36661 83853 92030 37414  9644]


array([[374656,      2,      5],
       [ 34965,     30,      8],
       [351116,     25,      6],
       [100018,     65,      4],
       [215475,     50,      6],
       [282967,     55,     14],
       [386465,     15,      5],
       [164423,     23,      7],
       [255720,     22,      8],
       [354212,     45,     11]])

11. Выведите процент рецептов, кол-во ингредиентов в которых меньше среднего.

In [388]:
len( minutes_n[minutes_n[:, 2] < np.average( top_100[:, 2] )] ) / len(minutes_n) * 100

58.802

12. Назовем "простым" такой рецепт, длительность выполнения которого не больше 20 минут и кол-во ингредиентов в котором не больше 5. Создайте версию датасета с дополнительным столбцом, значениями которого являются 1, если рецепт простой, и 0 в противном случае.

In [415]:
zeroz = np.zeros(len(minutes_n), dtype="int32").reshape(-1, 1)
zeroz[ np.logical_and( minutes_n[:, 2] <= 5, minutes_n[:, 1] <= 20 )  ] = 1
minutes_n_s = np.concatenate( (minutes_n, zeroz), axis=1)
minutes_n_s

array([[127244,     60,     16,      0],
       [ 23891,     25,      7,      0],
       [ 94746,     10,      6,      0],
       ...,
       [498432,     65,     15,      0],
       [370915,      5,      4,      1],
       [ 81993,     65,     14,      0]])

13. Выведите процент "простых" рецептов в датасете

In [421]:
sum(minutes_n_s[:, 3]) / len(minutes_n_s)

0.09552

14. Разделим рецепты на группы по следующему правилу. Назовем рецепты короткими, если их продолжительность составляет менее 10 минут; стандартными, если их продолжительность составляет более 10, но менее 20 минут; и длинными, если их продолжительность составляет не менее 20 минут. Создайте трехмерный массив, где нулевая ось отвечает за номер группы (короткий, стандартный или длинный рецепт), первая ось - за сам рецепт и вторая ось - за характеристики рецепта. Выберите максимальное количество рецептов из каждой группы таким образом, чтобы было возможно сформировать трехмерный массив. Выведите форму полученного массива.

In [463]:
shrt = minutes_n[ minutes_n[:, 1] < 10 ]
std  = minutes_n[ np.logical_and( 10 < minutes_n[:, 1], minutes_n[:, 1] < 20 ) ]
lng  = minutes_n[ minutes_n[:, 1] >= 20 ]
# print(np.ndarray(shrt, std, lng))

a = []
for i in [shrt, std, lng]:
    a.append(i)
a
np.asarray(a)
# np.concatenate( (shrt, std, lng) ).shape
# # np.vstack( [shrt, std, lng])
# np.array((shrt, std, lng))

[array([[ 67660,      5,      6],
        [366174,      7,      9],
        [204134,      5,      3],
        ...,
        [420725,      5,      3],
        [  4747,      1,      9],
        [370915,      5,      4]]),
 array([[ 33941,     18,      9],
        [446597,     15,      5],
        [ 81006,     12,      7],
        ...,
        [ 44120,     17,      5],
        [ 60756,     15,      5],
        [128811,     15,      4]]),
 array([[127244,     60,     16],
        [ 23891,     25,      7],
        [157911,     60,     14],
        ...,
        [287943,     65,     15],
        [498432,     65,     15],
        [ 81993,     65,     14]])]