# Numpy

Материалы:
* Макрушин С.В. "Лекция 1: Библиотека Numpy"
* https://numpy.org/doc/stable/user/index.html
* https://numpy.org/doc/stable/reference/index.html

## Задачи для совместного разбора

In [1]:
import numpy as np

1. Сгенерировать двухмерный массив `arr` размерности (4, 7), состоящий из случайных действительных чисел, равномерно распределенных в диапазоне от 0 до 20. Нормализовать значения массива с помощью преобразования вида  $𝑎𝑥+𝑏$  так, что после нормализации максимальный элемент масcива будет равен 1.0, минимальный 0.0

In [2]:
import random

def norm(array, element):
    return (element - min(array)) / (max(array) - min(array))


arr = np.array([[random.random()*random.randint(0,20) for i in range (7)] for i in range(4)])


print(arr)

for i in range(len(arr)):
    for j in range(len(arr[i])):
        arr[i][j] = norm(arr[i], arr[i][j])

print(arr)


[[ 1.89892674  0.45452251  0.82665415 11.81453128  2.24136119  1.64992115
   0.69165089]
 [ 5.50912328  0.78264436  5.43921577  3.8875273   0.4415906   5.53112208
   2.04599094]
 [ 6.82640624  0.82908887  3.00157933  8.55406029  0.19970096  4.47645696
  10.08541178]
 [ 0.77102998  0.         10.84779742  3.64920963  5.01539961  0.70458461
   0.1646918 ]]
[[0.12714816 0.02801092 0.06775903 1.         1.         1.
  0.68276484]
 [0.99567764 0.06701084 0.98318001 0.69920181 0.06855273 1.
  1.        ]
 [0.67033169 0.06366643 0.29315382 0.84719713 0.01357394 0.44310513
  1.        ]
 [0.0710771  0.         1.         0.72760097 1.         0.70458461
  0.1646918 ]]


2. Создать матрицу 8 на 10 из случайных целых (используя модуль `numpy.random`) чисел из диапозона от 0 до 10 и найти в ней строку (ее индекс и вывести саму строку), в которой сумма значений минимальна.

In [3]:
rng = np.random.default_rng()

arr2 = np.array([rng.integers(low=0, high=10, size=10) for i in range(8)])

print(arr2)

suM = [np.sum(i) for i in arr2]

miN = suM.index(np.min(suM))

print(miN, arr2[miN])

[[4 5 4 6 9 2 7 8 2 2]
 [3 1 3 0 6 3 9 0 9 3]
 [9 2 7 2 9 7 4 7 3 3]
 [0 8 1 9 0 1 5 9 9 6]
 [3 1 7 9 9 2 3 9 1 9]
 [7 9 7 7 6 2 5 8 8 4]
 [0 3 1 0 3 3 6 0 8 7]
 [1 7 3 9 6 5 5 1 7 1]]
6 [0 3 1 0 3 3 6 0 8 7]


3. Найти евклидово расстояние между двумя одномерными векторами одинаковой размерности.

In [4]:
a = np.array((-6, 3, 1))
b = np.array((413, 61, -341))

np.linalg.norm(a - b)

543.9567997552747

4. Решить матричное уравнение `A*X*B=-C` - найти матрицу `X`. Где `A = [[-1, 2, 4], [-3, 1, 2], [-3, 0, 1]]`, `B=[[3, -1], [2, 1]]`, `C=[[7, 21], [11, 8], [8, 4]]`.

In [11]:
A = np.array([[-1, 2, 4], [-3, 1, 2], [-3, 0, 1]])
B = np.array([[3, -1], [2, 1]])
C = np.array([[7, 21], [11, 8], [8, 4]])

print(np.linalg.inv(B) * -C * np.linalg.inv(A))



ValueError: operands could not be broadcast together with shapes (2,2) (3,2) 

## Лабораторная работа №1

Замечание: при решении данных задач не подразумевается использования циклов или генераторов Python, если в задании не сказано обратного. Решение должно опираться на использования функционала библиотеки `numpy`.

1. Файл `minutes_n_ingredients.csv` содержит информацию об идентификаторе рецепта, времени его выполнения в минутах и количестве необходимых ингредиентов. Считайте данные из этого файла в виде массива `numpy` типа `int32`, используя `np.loadtxt`. Выведите на экран первые 5 строк массива.

2. Вычислите среднее значение, минимум, максимум и медиану по каждому из столбцов, кроме первого.

3. Ограничьте сверху значения продолжительности выполнения рецепта значением квантиля $q_{0.75}$. 

4. Посчитайте, для скольких рецептов указана продолжительность, равная нулю. Замените для таких строк значение в данном столбце на 1.

5. Посчитайте, сколько уникальных рецептов находится в датасете.

6. Сколько и каких различных значений кол-ва ингредиентов присутвует в рецептах из датасета?

7. Создайте версию массива, содержащую информацию только о рецептах, состоящих не более чем из 5 ингредиентов.

8. Для каждого рецепта посчитайте, сколько в среднем ингредиентов приходится на одну минуту рецепта. Найдите максимальное значение этой величины для всего датасета

9. Вычислите среднее количество ингредиентов для топ-100 рецептов с наибольшей продолжительностью

10. Выберите случайным образом и выведите информацию о 10 различных рецептах

11. Выведите процент рецептов, кол-во ингредиентов в которых меньше среднего.

12. Назовем "простым" такой рецепт, длительность выполнения которого не больше 20 минут и кол-во ингредиентов в котором не больше 5. Создайте версию датасета с дополнительным столбцом, значениями которого являются 1, если рецепт простой, и 0 в противном случае.

13. Выведите процент "простых" рецептов в датасете

14. Разделим рецепты на группы по следующему правилу. Назовем рецепты короткими, если их продолжительность составляет менее 10 минут; стандартными, если их продолжительность составляет более 10, но менее 20 минут; и длинными, если их продолжительность составляет не менее 20 минут. Создайте трехмерный массив, где нулевая ось отвечает за номер группы (короткий, стандартный или длинный рецепт), первая ось - за сам рецепт и вторая ось - за характеристики рецепта. Выберите максимальное количество рецептов из каждой группы таким образом, чтобы было возможно сформировать трехмерный массив. Выведите форму полученного массива.